"""Research-only backtest foundation, replay, and lifecycle boundaries."""

from src.backtest.foundation import (
    REQUIRED_EXECUTION_ASSUMPTIONS,
    BacktestExecutionEvidenceUnavailable,
    BacktestFoundationError,
    BacktestRunMetadata,
    EvidenceClassification,
    ExecutionAssumption,
    ExecutionEvidence,
    assert_can_produce_performance_results,
    backtest_metadata_json,
    unavailable_execution_assumptions,
)
from src.backtest.lifecycle import (
    LifecycleEventType,
    LifecycleObservation,
    LifecycleSimulationMetadata,
    LifecycleState,
    LifecycleTransition,
    TradeLifecycleSimulation,
    TradeLifecycleSimulationError,
    build_trade_lifecycle_simulation,
    lifecycle_metadata_json,
    lifecycle_transitions_json,
)
from src.backtest.replay import (
    CandleReplay,
    CandleReplayError,
    CandleReplayMetadata,
    CandleReplayRow,
    build_candle_replay,
    candle_replay_metadata_json,
    candle_replay_rows_json,
)

__all__ = [
    "REQUIRED_EXECUTION_ASSUMPTIONS",
    "BacktestExecutionEvidenceUnavailable",
    "BacktestFoundationError",
    "BacktestRunMetadata",
    "CandleReplay",
    "CandleReplayError",
    "CandleReplayMetadata",
    "CandleReplayRow",
    "EvidenceClassification",
    "ExecutionAssumption",
    "ExecutionEvidence",
    "LifecycleEventType",
    "LifecycleObservation",
    "LifecycleSimulationMetadata",
    "LifecycleState",
    "LifecycleTransition",
    "TradeLifecycleSimulation",
    "TradeLifecycleSimulationError",
    "assert_can_produce_performance_results",
    "backtest_metadata_json",
    "build_candle_replay",
    "build_trade_lifecycle_simulation",
    "candle_replay_metadata_json",
    "candle_replay_rows_json",
    "lifecycle_metadata_json",
    "lifecycle_transitions_json",
    "unavailable_execution_assumptions",
]
